spring:
  application:
    name: craft
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 8599
  jpa:
    hibernate:
      ddl-auto: create
  show_sql: true
  properties:
    hibernate:
      format_sql: true
  database: mysql
  database-platform: org.hibernate.dialect.MysqlDialect
  servlet:
    multipart:
      max-file-size: 10MB         # Set maximum file size for individual uploads
      max-request-size: 10MB       # Set maximum request size for the entire request
server:
  error:
    include-message: never

 
